declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY?: string;
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID?: string;
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN?: string;
    NEXT_PUBLIC_CONTENTFUL_OWNER_NAME?: string;
    NEXT_PUBLIC_CONTENTFUL_EXPERIENCES_ENTRY_ID?: string;
    NEXT_PUBLIC_CONTENTFUL_CT_EXPERIENCES?: string;
    NEXT_PUBLIC_CONTENTFUL_PORTFOLIOS_ENTRY_ID?: string;
    NEXT_PUBLIC_CONTENTFUL_CT_PORTFOLIOS?: string;
    NEXT_PUBLIC_CONTENTFUL_SOCIAL_ENTRY_ID?: string;
    NEXT_PUBLIC_CONTENTFUL_CT_SOCIAL?: string;
  }
}
